### PR TITLE
Add Owlet into  FRP libs

### PR DESCRIPTION
**Pull request by jcouyang**
https://oyanglul.us/owlet

### CODE REVIEW

**Comment by ochrons** [comment]
For a new library there is no need to add old versions. Just use the latest.

**Comment by jcouyang** [comment]
Thanks @ochrons 
what's the release cycle like? when can I find the new lib live in scalafiddle.io ?

**Comment by jcouyang** [comment]
Thanks @ochrons now I can find owlet but when I choose it and run, it show me this error
```
ScalaFiddle.scala:-5: ERROR: Library us.oyanglul %%% owlet % 0.3.1 is not allowed
```

**Comment by ochrons** [comment]
Looks like the compiler instances had not picked up the new libraries, restarted them and now seems to work ok :)

**Comment by jcouyang** [comment]
yay it works, thanks @ochrons

**Pull request merged**
