### PR TITLE
Add sttp-circe library

### PR DESCRIPTION
**Pull request by adamw**
It's quite useful to be able to parse json, so the sttp-circe integration would be nice to have in the fiddle as well.

Hope I got the dependencies right, as I understand they all have to be enumerated explicitly?

### CODE REVIEW

**Comment by ochrons** [comment]
Wouldn't it make more sense to just have "sttp" also include sttp-circe? There's no special benefit in breaking these libraries into smaller subsets, just put everything together that makes sense :)

**Comment by adamw** [comment]
Makes sense :) I've had to drop 2.11 from the scala versions, though.

**Comment by ochrons** [comment]
No worries about 2.11, it will be dropped altogether once we have 2.13 working :)

**Comment by adamw** [comment]
Thanks! :)

Online in the docs now: https://sttp.softwaremill.com/en/latest/#try-sttp-client-in-your-browser

**Pull request merged**
