### PR TITLE
Add Slinky to web libraries

### PR DESCRIPTION
**Pull request by shadaj**

### CODE REVIEW

**Comment by ochrons** [comment]
Could you also provide a sample code, like the one on scalajs-react lib? It makes it easier for people to get started with these more complex libraries. The sample can go into this repository under the `samples` folder.

**Comment by shadaj** [comment]
@ochrons just added a sample!

**Comment by ochrons** [comment]
Excellent, thanks a lot!

**Comment by ochrons** [comment]
The sample has macro compilation errors, can you take a look and provide a fix, thanks!

**Pull request merged**
